---
- name: update hosts file
  hosts: ks-master,ks-nodes
  become: true
  tasks:
   - name: update hosts
     lineinfile:
       dest: /etc/hosts
       regexp: '.*{{ item }}$'
       line: "{{ hostvars[item].public_ip }} {{item}}"
       state: present
     with_items: "{{ groups.all }}"

- name: Deploy kubernetes Master
  hosts: ks-master
  become: true
  roles:
  - docker
  - kubernetes-master

- name: Deploy kubernetes Nodes
  hosts: ks-nodes
  become: true
  roles:
  - docker
  - kubernetes-node

 - name: Update hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].public_ip }} {{item}}"
    state: present
  with_items: "{{ groups.all }}"

