---
# tasks file for kube-master
- name: Include pre requisites
  include: pre-reqs.yml

- name: Install docker
  include: docker.yml

- name: Include install file
  include: install.yml

- name: Init kubeadm
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kube_out

- name: set fact
  set_fact:
      node_cmd: "{{ kube_out.stdout_lines[-1] }}"

- name: using cluster
  shell: "{{ item }}"
  with_items:
      - "mkdir -p $HOME/.kube"
      - "sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
      - "sudo chown $(id -u):$(id -g) $HOME/.kube/config"
  become: false

- name: using cluster
  shell: "{{ item }}"
  with_items:
      - "mkdir -p $HOME/.kube"
      - "cp -i /etc/kubernetes/admin.conf $HOME/.kube/config"
      - "chown $(id -u):$(id -g) $HOME/.kube/config"

- name: sysctl setting
  shell: sysctl net.bridge.bridge-nf-call-iptables=1
  ignore_errors: true

- name: setup flannel
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
  
- name: enable kubelet service
  service:
     name: kubelet
     state: restarted
     enabled: yes
  when: ansible_distribution == 'CentOS'
