---
# tasks file for kube-master
- name: Include pre requisites
  include: pre-reqs.yml

- name: Install docker
  include: docker.yml

- name: Include install file
  include: install.yml

- name: join to cluster
  shell: "{{ hostvars['ks-master']['node_cmd'] }}"

